// This file will be auto-generated by Supabase CLI
// For now, we'll define the basic types manually
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > types/database.ts
// to generate types from your actual database schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string;
          display_name: string | null;
          avatar_url: string | null;
          featured_map_ids: string[] | null;
          created_at: string;
          updated_at: string;
          is_admin: boolean;
        };
        Insert: {
          id: string;
          username: string;
          display_name?: string | null;
          avatar_url?: string | null;
          featured_map_ids?: string[] | null;
          created_at?: string;
          updated_at?: string;
          is_admin?: boolean;
        };
        Update: {
          id?: string;
          username?: string;
          display_name?: string | null;
          avatar_url?: string | null;
          featured_map_ids?: string[] | null;
          created_at?: string;
          updated_at?: string;
          is_admin?: boolean;
        };
      };
      maps: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          subtitle: string | null;
          config: Json;
          is_published: boolean;
          thumbnail_url: string | null;
          vote_score: number;
          view_count: number;
          published_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          subtitle?: string | null;
          config: Json;
          is_published?: boolean;
          thumbnail_url?: string | null;
          vote_score?: number;
          view_count?: number;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          subtitle?: string | null;
          config?: Json;
          is_published?: boolean;
          thumbnail_url?: string | null;
          vote_score?: number;
          view_count?: number;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      votes: {
        Row: {
          id: string;
          user_id: string;
          map_id: string;
          value: number; // -1 or 1
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          map_id: string;
          value: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          map_id?: string;
          value?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      comments: {
        Row: {
          id: string;
          user_id: string;
          map_id: string;
          content: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          map_id: string;
          content: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          map_id?: string;
          content?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      rate_limits: {
        Row: {
          user_id: string;
          action_type: string;
          request_timestamps: Json;
          window_start: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          action_type: string;
          request_timestamps?: Json;
          window_start?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          action_type?: string;
          request_timestamps?: Json;
          window_start?: string;
          updated_at?: string;
        };
      };
      follows: {
        Row: {
          follower_id: string;
          following_id: string;
          created_at: string;
        };
        Insert: {
          follower_id: string;
          following_id: string;
          created_at?: string;
        };
        Update: {
          follower_id?: string;
          following_id?: string;
          created_at?: string;
        };
      };
      api_keys: {
        Row: {
          id: string;
          user_id: string;
          key_prefix: string;
          key_hash: string;
          name: string;
          tier: string;
          is_active: boolean;
          last_used_at: string | null;
          created_at: string;
          expires_at: string | null;
          rate_limit_override: Json | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          key_prefix: string;
          key_hash: string;
          name: string;
          tier?: string;
          is_active?: boolean;
          last_used_at?: string | null;
          created_at?: string;
          expires_at?: string | null;
          rate_limit_override?: Json | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          key_prefix?: string;
          key_hash?: string;
          name?: string;
          tier?: string;
          is_active?: boolean;
          last_used_at?: string | null;
          created_at?: string;
          expires_at?: string | null;
          rate_limit_override?: Json | null;
        };
      };
      api_usage: {
        Row: {
          id: string;
          api_key_id: string;
          user_id: string;
          endpoint: string;
          method: string;
          status_code: number;
          resource_type: string | null;
          credits_used: number;
          request_metadata: Json | null;
          response_time_ms: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          api_key_id: string;
          user_id: string;
          endpoint: string;
          method: string;
          status_code: number;
          resource_type?: string | null;
          credits_used?: number;
          request_metadata?: Json | null;
          response_time_ms?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          api_key_id?: string;
          user_id?: string;
          endpoint?: string;
          method?: string;
          status_code?: number;
          resource_type?: string | null;
          credits_used?: number;
          request_metadata?: Json | null;
          response_time_ms?: number | null;
          created_at?: string;
        };
      };
      feedback: {
        Row: {
          id: string;
          user_id: string | null;
          session_id: string | null;
          trigger_type: string;
          trigger_context: Json | null;
          overall_rating: number | null;
          nps_score: number | null;
          use_cases: string[] | null;
          pain_points: string[] | null;
          feature_ratings: Json | null;
          open_feedback: string | null;
          allow_followup: boolean;
          created_at: string;
          user_agent: string | null;
          page_url: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          session_id?: string | null;
          trigger_type: string;
          trigger_context?: Json | null;
          overall_rating?: number | null;
          nps_score?: number | null;
          use_cases?: string[] | null;
          pain_points?: string[] | null;
          feature_ratings?: Json | null;
          open_feedback?: string | null;
          allow_followup?: boolean;
          created_at?: string;
          user_agent?: string | null;
          page_url?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          session_id?: string | null;
          trigger_type?: string;
          trigger_context?: Json | null;
          overall_rating?: number | null;
          nps_score?: number | null;
          use_cases?: string[] | null;
          pain_points?: string[] | null;
          feature_ratings?: Json | null;
          open_feedback?: string | null;
          allow_followup?: boolean;
          created_at?: string;
          user_agent?: string | null;
          page_url?: string | null;
        };
      };
      feedback_tracking: {
        Row: {
          id: string;
          user_id: string | null;
          session_id: string | null;
          last_prompt_at: string | null;
          last_submitted_at: string | null;
          prompt_count: number;
          dismiss_count: number;
          opted_out: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          session_id?: string | null;
          last_prompt_at?: string | null;
          last_submitted_at?: string | null;
          prompt_count?: number;
          dismiss_count?: number;
          opted_out?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          session_id?: string | null;
          last_prompt_at?: string | null;
          last_submitted_at?: string | null;
          prompt_count?: number;
          dismiss_count?: number;
          opted_out?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          recipient_id: string;
          actor_id: string;
          type: 'FOLLOW' | 'MAP_POST' | 'COMMENT' | 'LIKE';
          resource_id: string | null;
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          recipient_id: string;
          actor_id: string;
          type: 'FOLLOW' | 'MAP_POST' | 'COMMENT' | 'LIKE';
          resource_id?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          recipient_id?: string;
          actor_id?: string;
          type?: 'FOLLOW' | 'MAP_POST' | 'COMMENT' | 'LIKE';
          resource_id?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
      };
      feature_flags: {
        Row: {
          id: string;
          key: string;
          name: string;
          description: string | null;
          enabled_development: boolean;
          enabled_production: boolean;
          enabled_for_users: string[] | null;
          enabled_percentage: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          name: string;
          description?: string | null;
          enabled_development?: boolean;
          enabled_production?: boolean;
          enabled_for_users?: string[] | null;
          enabled_percentage?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          name?: string;
          description?: string | null;
          enabled_development?: boolean;
          enabled_production?: boolean;
          enabled_for_users?: string[] | null;
          enabled_percentage?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      page_events: {
        Row: {
          id: string;
          user_id: string | null;
          session_id: string | null;
          event_type: string;
          event_name: string | null;
          page_url: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          session_id?: string | null;
          event_type: string;
          event_name?: string | null;
          page_url?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          session_id?: string | null;
          event_type?: string;
          event_name?: string | null;
          page_url?: string | null;
          metadata?: Json;
          created_at?: string;
        };
      };
      orders: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          user_id: string | null;
          design_id: string;
          variant_id: number;
          quantity: number;
          stripe_payment_intent_id: string | null;
          stripe_payment_status: string | null;
          amount_total: number | null;
          printful_order_id: number | null;
          status: 'pending' | 'paid' | 'fulfilled' | 'failed';
          shipping_name: string | null;
          shipping_address_line1: string | null;
          shipping_address_line2: string | null;
          shipping_city: string | null;
          shipping_state: string | null;
          shipping_zip: string | null;
          shipping_country: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id?: string | null;
          design_id: string;
          variant_id: number;
          quantity?: number;
          stripe_payment_intent_id?: string | null;
          stripe_payment_status?: string | null;
          amount_total?: number | null;
          printful_order_id?: number | null;
          status?: 'pending' | 'paid' | 'fulfilled' | 'failed';
          shipping_name?: string | null;
          shipping_address_line1?: string | null;
          shipping_address_line2?: string | null;
          shipping_city?: string | null;
          shipping_state?: string | null;
          shipping_zip?: string | null;
          shipping_country?: string | null;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id?: string | null;
          design_id?: string;
          variant_id?: number;
          quantity?: number;
          stripe_payment_intent_id?: string | null;
          stripe_payment_status?: string | null;
          amount_total?: number | null;
          printful_order_id?: number | null;
          status?: 'pending' | 'paid' | 'fulfilled' | 'failed';
          shipping_name?: string | null;
          shipping_address_line1?: string | null;
          shipping_address_line2?: string | null;
          shipping_city?: string | null;
          shipping_state?: string | null;
          shipping_zip?: string | null;
          shipping_country?: string | null;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      notification_type: 'FOLLOW' | 'MAP_POST' | 'COMMENT' | 'LIKE';
    };
  };
}

